#macro ABS_MAP  

enum L
{
	AMANDINE_DEADEND,
	BACK_TABLE,
	BACK_WATER_TOWER,
	BENCH_AGAINST_WALL,
	BLANK_WALL,
	COLUMN,
	CORNER_FOUNTAIN,
	FAKE_RUE_BLUE,
	FRONT_BENCH,
	GARAGE_HOTEL,
	JULIEN_DOOR,
	JULIEN_STAIRS,
	POLICE_STATION,
	RUE_BLUE,
	RUINES,
	STADIUM_ENTRANCE,
	STAIRS_1_2,
	STATION_BALCONY,
	STEEL_STAIRS,
	VEGETAL_DOME_HALLWAY,
	WATER_TOWER,
	WATER_TOWER_BENCH,
	Y_CHURCH_CROSSROADS,
	
}

enum CONNAISSANCE_LIEU{VISITE, JUXTAPOSE, INCONNU}

function add_lieu(_room, _x, _y, _connection = [], _connu = CONNAISSANCE_LIEU.VISITE)
{
	lieu[nbLieux] = {piece : _room, xMap : _x ABS_MAP, yMap : _y ABS_MAP, connections : _connection, connu : _connu}
	nbLieux ++;
}


function init_map()
{ 
	mapIsUpdated = false;
	
	nbLieux = 0;
	add_lieu(P_AMANDINE_DEADEND, 838, 826);
	add_lieu(P_RUE_BLUE, 922, 757);
	add_lieu(P_COLUMN, 527, 593,);
	add_lieu(P_FRONT_BENCH, 1019, 554);
	add_lieu(P_BLANK_WALL, 888, 946);
	add_lieu(P_FAKE_RUE_BLUE, 906, 710);
	add_lieu(P_VEGETAL_DOME_HALLWAY, 504, 746);
	add_lieu(P_WATER_TOWER_BENCH, 1156, 607);
	
	
	/*
	add_lieu(L.BACK_TABLE,  P_BACK_TABLE,866,462, [L.AMANDINE_DEADEND, L.BENCH_AGAINST_WALL]);
	add_lieu(L.BACK_WATER_TOWER, P_BACK_WATER_TOWER, 931, 555, [L.BENCH_AGAINST_WALL]);
	 
	*/
}