#macro ABS_MAP  

enum L
{
	AMANDINE_DEADEND,
	BACK_TABLE,
	BACK_WATER_TOWER,
	BENCH_AGAINST_WALL,
	BLANK_WALL,
	COLUMN,
	CORNER_FOUNTAIN,
	FAKE_RUE_BLUE,
	FRONT_BENCH,
	GARAGE_HOTEL,
	JULIEN_DOOR,
	JULIEN_STAIRS,
	POLICE_STATION,
	RUE_BLUE,
	RUINES,
	STADIUM_ENTRANCE,
	STAIRS_1_2,
	STATION_BALCONY,
	STEEL_STAIRS,
	VEGETAL_DOME_HALLWAY,
	WATER_TOWER,
	WATER_TOWER_BENCH,
	Y_CHURCH_CROSSROADS,
	
}

enum CONNAISSANCE_LIEU{VISITE, JUXTAPOSE, INCONNU}

function add_lieu(_enumeration, _room, _x, _y, _connection, _connu = CONNAISSANCE_LIEU.INCONNU)
{
	lieu[_enumeration] = {piece : _room, xMap : _x ABS_MAP, yMap : _y ABS_MAP, connections : _connection, connu : _connu}
}


function init_map()
{ 
	add_lieu(L.AMANDINE_DEADEND, P_AMANDINE_DEADEND, 836, 543, [L.BACK_TABLE, L.BENCH_AGAINST_WALL]);
	add_lieu(L.BACK_TABLE,  P_BACK_TABLE,866,462, [L.AMANDINE_DEADEND, L.BENCH_AGAINST_WALL]);
	add_lieu(L.BACK_WATER_TOWER, P_BACK_WATER_TOWER, 931, 555, [L.BENCH_AGAINST_WALL]);
	add_lieu(L.BENCH_AGAINST_WALL, P_BENCH_AGAINST_WALL,95, 471, [L.AMANDINE_DEADEND, L.BACK_TABLE, L.AMANDINE_DEADEND]);
	add_lieu(L.BLANK_WALL, P_POLICE_STATION,200,200,[L.AMANDINE_DEADEND], CONNAISSANCE_LIEU.JUXTAPOSE);
	
}