shader_set(sh_crt_screen);
shader_set_uniform_f_array(uinform_params_of_the_shader, params);
gpu_set_blendenable(false);
draw_set_alpha(1);
var _horizontal_scaling = window_get_width()/GAME_WIDTH;
var _vertical_scaling = window_get_height()/GAME_HEIGHT;
var _application_surface_x = COMPUTER_SCREEN_X_1*_horizontal_scaling;
var _application_surface_y = COMPUTER_SCREEN_Y_1*_vertical_scaling;
var _application_surface_width = (COMPUTER_SCREEN_X_2 - COMPUTER_SCREEN_X_1)*_horizontal_scaling;
var _application_surface_height = (COMPUTER_SCREEN_Y_2 - COMPUTER_SCREEN_Y_1)*_vertical_scaling;
draw_surface_stretched(application_surface, _application_surface_x, _application_surface_y, _application_surface_width, _application_surface_height );
gpu_set_blendenable(true);
shader_reset();