enum CASE_STRING_DEPLOYMENT_STATE
{
	WAITING_FOR_DEPLOYMENT,
	DEPLOYMENT_STARTED,
	DEPLOYMENT_DONE,
	DESTROYING,
	
}
#macro DEPLOYMENT_DURATION CRIME_DELAY_FRAMES
if no_animation
{
	deployment_timer = DEPLOYMENT_DURATION;
	deployment_state = CASE_STRING_DEPLOYMENT_STATE.DEPLOYMENT_DONE;
}